### ISSUE TITLE
Add SQL database binding

### ISSUE THREAD

**Issue by b-gauthier** [Jutta-Proto/gtk-ui#2]
Hello,
I would like to add a SQL database binding for this application comprising the following functions:
- retrieving the username and parameters from the database based on the NFC card ID 
- log coffee machine usage to database

Where should I start ? 
Thanks !

**Comment by COM8** [comment]
I'd say you are best to start inside the [NfcCardReader](https://github.com/Jutta-Proto/gtk-ui/blob/bt/src/backend/NfcCardReader.cpp) class.
Here the card detected event gets triggered: https://github.com/Jutta-Proto/gtk-ui/blob/6e992a0bd0d79cf8d2bdecf3ed17c771519f116d/src/backend/NfcCardReader.cpp#L128-L130

Which then results in the UI loading the new profile: https://github.com/Jutta-Proto/gtk-ui/blob/6e992a0bd0d79cf8d2bdecf3ed17c771519f116d/src/ui/windows/MainWindow.cpp#L276-L281

**Comment by b-gauthier** [comment]
Thanks for your quick response, I will investigate what you suggested. 

Additionally, I'm using the serial protocol (not the BT or WIFI one). I noticed some improvements on the BT branch of GTK-UI (such as the status bar) that are not present on the serial one. Do you think I could export these new widgets to the serial one or the BT dongle itself is necessary for those new functions ? 

Last question : an easier way to log the coffee machine usage per user (instead of connection a SQL database) would be to simply wright it in a .json or similar text file (basically I want to count the number of coffee per user/card id). I guess I would need to implement somewhere out there : 
https://github.com/Jutta-Proto/gtk-ui/blob/4797e7129dcabb5f47ea6964db2487aac79912af/src/ui/widgets/CoffeeSelectionWidget.cpp#L69
Thanks again for you help !

**Comment by COM8** [comment]
### Extending
Then the basic JSON serializer currently build in should be fine.  You can just catch the `on_coffee_button_clicked` events and do something like this:
```c#
profile->coffee_count++; // Increment your counter
backend::storage::get_user_profile_storage_instance().write_profiles(); // Write the changes to disc
```

For the additional metrics you need to add them here to the profile:
https://github.com/Jutta-Proto/gtk-ui/blob/4797e7129dcabb5f47ea6964db2487aac79912af/src/backend/storage/UserProfileStorage.hpp#L12-L37

Then extend the `from_json` and `to_json` calls here:
https://github.com/Jutta-Proto/gtk-ui/blob/4797e7129dcabb5f47ea6964db2487aac79912af/src/backend/storage/UserProfileStorage.cpp#L52-L61


### Porting Widgets
No, this is not possible right now since the [serial protocol](https://github.com/Jutta-Proto/protocol-cpp) currently does not have this functionality. **But** we are working on it!

**Comment by COM8** [comment]
And once you are done, feel free to create a PR, so everyone can enjoy your enhancements 😊.

**Comment by COM8** [comment]
Closing this one since it looks to be solved :)
